### ISSUE TITLE
Field 'count' doesn't have a default value

### ISSUE THREAD

**Issue by pwlgrzs** [danmed/PStatus#1]
Hello,

SQL query:
INSERT INTO servers (device, ip, info, purpose) VALUES ('Google', '8.8.8.8', 'Google DNS', '')

MySQL said: Documentatio
#1364 - Field 'count' doesn't have a default value

I'm getting this in 2 separate databases.

**Comment by danmed** [comment]
I assume this is adding a new server?

I've updated it to add a default value of 0 when the record is created... can you try it now?

**Comment by pwlgrzs** [comment]
Correct, when adding new server.

Now same happens to 'ups' field, so my guess is other fields touched when adding will come back with the same message.

**Comment by danmed** [comment]
OK, give me a few minutes

**Comment by danmed** [comment]
I've adjusted the database design to included default values (or NULL) for the date fields.. would you mind testing it?

**Comment by pwlgrzs** [comment]
Retried on fresh 'install':

Error: INSERT INTO servers (device, ip, info, purpose, count) VALUES ('Google', '8.8.8.8', 'Google DNS', '', '0')
Field 'ups' doesn't have a default value

**Comment by danmed** [comment]
Hey, thanks for testing again.. i've just updated the table def to allow NULL in those fields.. mind trying again?

**Comment by pwlgrzs** [comment]
Good on my end now!

**Comment by danmed** [comment]
Awesome.. thanks for your changes too!

I've found a bug which i'll have to sort out with the datatable.. if you have more than 10 devices, then the subsequent pages or search results don't highlight green or red when online.. i may be able to detect it differently with bootstrap but i'll have to look.
